FROM python:3

RUN git clone https://github.com/Francosantander/um-programacion-i-2020/tree/master/58105-Santander-Franco/tps/tp2/ej2
WORKDIR /ej2

RUN pip install -r requirements.txt

CMD [ "python3", "test_completo.py"]