FROM python:3

RUN git clone https://github.com/igncarrillo/um-programacion-i-2020.git

WORKDIR /um-programacion-i-2020/59289-Ignacio-Carrillo/TP3/ej2_ej3

#COPY requirements.txt /um-programacion-i-2020/59289-Ignacio-Carrillo/TP3/ej2_ej3

#RUN pip install -r requirements.txt

COPY . /um-programacion-i-2020/59289-Ignacio-Carrillo/TP3/ej2_ej3

CMD ["python","./tests.py"]
