FROM python:3
RUN git clone https://github.com/santigg19/um-programacion-i-2020
WORKDIR /um-programacion-i-2020/58157 - Graffigna, Santiago/TP3
RUN pip install -r requirements.txt
CMD ["python", "./test_atm.py"]